### ISSUE TITLE
recipe for target 'CMakeFiles/ObjSLAM.dir/src/cvplot/window.cc.o' failed

### ISSUE THREAD

**Issue by WhoisYaoZhang** [halajun/VDO_SLAM#10]
Dear authors,

When compile the work, I have the following two errors, do you know how to deal with them?

recipe for target 'CMakeFiles/ObjSLAM.dir/src/cvplot/window.cc.o' failed

CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ObjSLAM.dir/all' failed

make[1]: *** [CMakeFiles/ObjSLAM.dir/all] Error 2

Makefile:83: recipe for target 'all' failed

**Comment by niconi23333** [comment]
I met the same problem...Could you share how you solve it?
