### ISSUE TITLE
How to solve this problem，thank you

### ISSUE THREAD

**Issue by xiaohang212** [halajun/VDO_SLAM#11]
[100%] Linking CXX executable ../example/vdo_slam
CMakeFiles/vdo_slam.dir/example/vdo_slam.cc.o: In function `main':
vdo_slam.cc:(.text.startup+0xc08): undefined reference to `cv::optflow::readOpticalFlow(cv::String const&)'
collect2: error: ld returned 1 exit status
CMakeFiles/vdo_slam.dir/build.make:115: recipe for target '../example/vdo_slam' failed
make[2]: *** [../example/vdo_slam] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/vdo_slam.dir/all' failed
make[1]: *** [CMakeFiles/vdo_slam.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by halajun** [comment]
Hi, @xiaohang212. Looks like it has something to do with the function of "cv::optflow::readOpticalFlow()"; Please check your opencv version if it support this function, shouldn't be a difficult issue to fix. Hope this helps.

**Comment by MinaHenein** [comment]
Hi @xiaohang212,
Please let us know if you solved this issue.

**Comment by xiaohang212** [comment]
Problem solved, thank you～

**Comment by Duke1325** [comment]
@xiaohang212 
I met the same issue, could you share the way to solve it? Thanks!

**Comment by colin-de** [comment]
@xiaohang212 
hello xiaohang, could u please tell me how did u solve this issue?
I still have the problem as you before.
Thanks! :)

**Comment by xiaohang212** [comment]
> @xiaohang212 你好小航，你能告诉我你是怎么解决这个问题的吗？ 我还是和你以前一样的问题。 谢谢！:)

I downgraded Opencv version, OPENCV3.4.0 + contrib may work.But I didn't get to the bottom of why

**Comment by Duke1325** [comment]
您的邮件我已经收到，谢谢！

**Comment by Duke1325** [comment]
您的邮件我已经收到，谢谢！
