### ISSUE TITLE
The Method to get the Ground truth of camera poses

### ISSUE THREAD

**Issue by Maple-Yang-neu** [halajun/VDO_SLAM#13]
Dr. Henein:
     I'm sorry to bother you, When I used KITTI Tracking data set to verify my own algorithm, I found that KITTI raw provided IMU and GPS data instead of 6 DoF poses .We would sincerely appreciate it if you were willing to share some experience about these problems.
      Looking forward to your reply！

**Comment by halajun** [comment]
Hi @Maple-Yang-neu. You need to transfer the IMU/GPS data to get the ground truth pose. Please refer to the readme.txt file in the devkit raw of the KITTI raw dataset. Hope this helps.
