### ISSUE TITLE
How to get the Ground Truth Camera Pose , Object Pose and the times.txt 

### ISSUE THREAD

**Issue by Liuxuweilxw** [halajun/VDO_SLAM#15]
I may can get the bounding box (B1-B4) from Mask-RCNN  ,but I don't know how to get others data. And there is no times.txt  in KITTI tracking dataset.  Looking forward to your reply. Thanks.

**Comment by halajun** [comment]
Hi, @Liuxuweilxw. The ground truth camera pose is in the "data_tracking_oxts" folder if you have downloaded it from the KITTI Tracking Dataset. the files inside saves the GPS/IMU data, where you can extract the ground truth camera pose. For the ground truth object pose, it is in the "data_tracking_label_2" if you have downloaded. Please refer to the readme file in this dataset for more details. Finally for the "times.txt", it is just used for organizing the image frames, you can generate it yourself with any frame rate (e.g., 10hz), it does not affect anything in the code. Hope this helps.

**Comment by Liuxuweilxw** [comment]
Thanks for your help !


 
---Original---
From: "Jun Zhang ***@***.***&gt;
Date: 2021/4/1 06:49:35
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [halajun/VDO_SLAM] How to get the Ground Truth Camera Pose , Object Pose and the times.txt  (#15)




 
Hi, @Liuxuweilxw. The ground truth camera pose is in the "data_tracking_oxts" folder if you have downloaded it from the KITTI Tracking Dataset. the files inside saves the GPS/IMU data, where you can extract the ground truth camera pose. For the ground truth object pose, it is in the "data_tracking_label_2" if you have downloaded. Please refer to the readme file in this dataset for more details. Finally for the "times.txt", it is just used for organizing the image frames, you can generate it yourself with any frame rate (e.g., 10hz), it does not affect anything in the code. Hope this helps.
