### ISSUE TITLE
how to generate the depth map?

### ISSUE THREAD

**Issue by shqfeng** [halajun/VDO_SLAM#16]
I try to use SGBM to calculate the depth, but it dose not work! Can you share the project of depth map generation?

**Comment by Liuxuweilxw** [comment]
Try monodepth2 https://github.com/nianticlabs/monodepth2

**Comment by Liuxuweilxw** [comment]
It's for monocular

**Comment by shqfeng** [comment]
thanks for your reply！ how to generate the "depth" folder of KITTI stereo dataset, I use the opencv SGBM, hower, the results is bad, can you share this work? thanks very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月29日(星期一) 晚上9:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [halajun/VDO_SLAM] how to generate the depth map? (#16)





 
It's for monocular

**Comment by Liuxuweilxw** [comment]
Sorry, I make wrong. I used monodepth to generate depth for single image, not for stereo

**Comment by halajun** [comment]
Hi, @shqfeng. the method SGBM generates disparity map, not depth map. You need to compute the depth value from disparity by [depth = baseline*focal_lenth/(disparity/depth_factor)]. For your reference, I use the [method](https://ttic.uchicago.edu/~dmcallester/SPS/index.html) of the paper "Efficient Joint Segmentation, Occlusion Labeling, Stereo and Flow Estimation" to calculate the disparity map. Hope this helps.

**Comment by shqfeng** [comment]
thanks！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jun Zhang ***@***.***&gt;; 
发送时间: 2021年4月1日(星期四) 上午6:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [halajun/VDO_SLAM] how to generate the depth map? (#16)





 
Hi, @shqfeng. the method SGBM generates disparity map, not depth map. You need to compute the depth value from disparity by [depth = baseline*focal_lenth/(disparity/depth_factor)]. For your reference, I use the method of the paper "Efficient Joint Segmentation, Occlusion Labeling, Stereo and Flow Estimation" to calculate the disparity map. Hope this helps.
