### ISSUE TITLE
is it possible to evaluate the size of 3d bounding box in your pipeline?

### ISSUE THREAD

**Issue by zechendev** [halajun/VDO_SLAM#3]
Hi, thank you for your sharing the code, I wonder if it is possible to evaluate the size of 3d bounding box in your pipeline?
If it is possible? where should I start?

**Comment by MinaHenein** [comment]
Hi @zechendev,
1- our method estimates an SE(3) rigid object motion per time step for each detected moving object in the scene, however, we do not explicitly estimate an object pose or dimensions.
2- to answer your question, you can evaluate the object poses by using the ground-truth pose of the object when it is first detected by the algorithm and propagate the motions estimated by our algorithm to obtain the consecutive object poses.
3- As said earlier, we do not estimate for a size of the bounding box, so dimensions of the 3D bounding box can not evaluated using our pipeline. 
Hope this makes things clear and please feel free to ask any more questions.
