### ISSUE TITLE
How did you calculate or where did you download depth images for kitti sequence?

### ISSUE THREAD

**Issue by andrey1908** [halajun/VDO_SLAM#4]
Hi, I want to try running your algorithm on some other kitti sequences, but I could not find where to download depth images or how to calculate them from velodyne points. Could you please tell how did you get depth images for kitti sequence?

**Comment by halajun** [comment]
Hi @andrey1908 . We generate the depth map in two ways depending on the input image sequence. If the input is stereo images, we calculate the depth(or disparity) map using off-the-shelf stereo depth estimation method for the KITTI sequence. If the input is monocular image, we compute the depth map using off-the-shelf learning-based single image depth estimation method. Please see the VDO-SLAM paper for the specific methods we applied if you would like to know more details.  Hope this may help.
