### ISSUE TITLE
Excellent open source work. In image preprocessing, what network is used for instance segmentation? What method is used to calculate the optical flow?

### ISSUE THREAD

**Issue by seushengchao** [halajun/VDO_SLAM#5]
Excellent open source work. In image preprocessing, what network is used for instance segmentation? What method is used to calculate the optical flow?

**Comment by halajun** [comment]
Thank you for your interest, @seushengchao. In image preprocessing, we used Mask R-CNN for instance segmentation and PWC-NET for optical flow calculation. But you could also use other state-of-the-art methods instead. Hope this will help.
