### ISSUE TITLE
Segment error (core dumped)

### ISSUE THREAD

**Issue by Alwen-V** [halajun/VDO_SLAM#53]
I admire your excellent work very much. I have a question that urgently needs your answer: After I successfully compiled the executable file vdo_slam, the terminal immediately reported "Segment error (core dumped)" after I entered the instruction. This is different from orb-slam series, which reports an error immediately without starting to run.
My environment is:
ubuntu18.04
opencv3.4.0
your dependencies/g2o
VTK6.3.0
Ceres1.13.0
![1](https://github.com/halajun/VDO_SLAM/assets/57043989/95861978-0cfe-46b7-8209-7c30fe964284)

**Comment by Alwen-V** [comment]
![11](https://github.com/halajun/VDO_SLAM/assets/57043989/653e6c17-64e4-4d07-8d9a-df9b1489cdce)

**Comment by hu-xue** [comment]
I had met this error. It may be the ‘CSPARSE’ in the end of cmake_modules should be 'CSparse'. But it is long time ago, I suggest you try it, maybe can fix it.
