### ISSUE TITLE
In the paper, you test the RGB-D version of “VDO-SLAM” on the "KITTI Tracking Dataset", I notice that this dataset only provides the Velodyne point clouds, but does not directly provide the depth map.  What method do you adapt to convert the point cloud data into the depth map?

### ISSUE THREAD

**Issue by seushengchao** [halajun/VDO_SLAM#7]
In the paper, you test the RGB-D version of “VDO-SLAM” on the "KITTI Tracking Dataset", I notice that this dataset only provides the Velodyne point clouds, but does not directly provide the depth map.  What method do you adapt to convert the point cloud data into the depth map?

**Comment by halajun** [comment]
Hi @seushengchao. We didn't use the provided Velodyne point cloud data to generate depth map in the KITTI Tracking dataset. Instead, we use the stereo images, which is also provided in the dataset, to generate the depth map through stereo depth estimation. Hope this helps.
